# -*- coding: utf-8 -*-
"""
Created on Fri Aug 26 21:34:21 2022

@author: Martín Carlos Araya <martinaraya@gmail.com>
"""

from unyts import convert, clean_memory, set_unit, set_conversion
from pandas import read_excel
from math import isnan
from unyts.converter import _apply_conversion, _get_conversion, _converter, _clean_print_conversion_path, convert_for_SimPandas, convertible
from unyts.database import units_network as UnNe
import numpy as np
import pytest

clean_memory()


def test__get_conversion():
    """Validate low-level conversion path discovery for representative cases."""
    assert _get_conversion(3, 'meter', 'meter') == (3, [UnNe.get_node('meter')])
    assert _get_conversion('16/06/1969', 'date', 'DATE') == ('16/06/1969', [UnNe.get_node('date'), UnNe.get_node('DATE')])
    assert _get_conversion(2, 'foot', None) == (2, [])
    assert _get_conversion(3, None, 'meter') == (3, [])
    assert _get_conversion(4, None, None) == (4, [None])
    assert _get_conversion(5, 'fraction', 'meter') == (5, [])
    assert _get_conversion(0.25, 'fraction', 'percent') == (25.0, ['*', 100])
    assert _get_conversion(0.25, 'percent', 'fraction') == (0.0025, ['/', 100])
    assert _get_conversion(0.25, 'dimensionless', 'fraction') == (0.25, [])
    assert _get_conversion(0.01, 'F/ft', 'C/m') == (0.018226888305628464, ['*', 0.5555555555555556, '/', 1,
                                                                           UnNe.get_node('ft'),
                                                                           UnNe.get_node('foot'),
                                                                           UnNe.get_node('yard'),
                                                                           UnNe.get_node('meter'),
                                                                           UnNe.get_node('m')])
    assert _get_conversion(0.33, 'fraction', 'ft/ft') == (0.33, [])
    assert _get_conversion(0.33, 'ft3/ft3', 'fraction') == (0.33, [])
    assert _get_conversion(10, 'scf/stb', 'stb/scf') == (1/10, ['1/'])
    assert _get_conversion(1, 'm', 'cm') == (100, [UnNe.get_node('m'), UnNe.get_node('cm')])
    assert _get_conversion(1, 'meter', 'inch') == (39.37007874015748,
                                                   [UnNe.get_node('meter'),
                                                    UnNe.get_node('yard'),
                                                    UnNe.get_node('foot'),
                                                    UnNe.get_node('inch')])


def test__converter():
    """Validate converter outputs both value and path components."""
    assert _converter(0.433, 'psi/ft', 'bar/m') == (0.09794717545606699, [UnNe.get_node('psi'),
                                                                          UnNe.get_node('bar'),
                                                                          '/', 1,
                                                                          UnNe.get_node('ft'),
                                                                          UnNe.get_node('foot'),
                                                                          UnNe.get_node('yard'),
                                                                          UnNe.get_node('meter'),
                                                                          UnNe.get_node('m')])


def test__apply_conversion():
    """Validate application of conversion paths generated by _get_conversion."""
    conv, conv_path = _get_conversion(3, 'meter', 'meter')
    assert _apply_conversion(3, conv_path) == conv

    conv, conv_path = _get_conversion(0.25, 'fraction', 'percent')
    assert _apply_conversion(0.25, conv_path) == conv

    conv, conv_path = _get_conversion(0.25, 'percent', 'fraction')
    assert _apply_conversion(0.25, conv_path) == conv

    conv, conv_path = _get_conversion(0.25, 'dimensionless', 'fraction')
    assert _apply_conversion(0.25, conv_path) == conv

    conv, conv_path = _get_conversion(10, 'scf/stb', 'stb/scf')
    assert _apply_conversion(10, conv_path) == conv

    conv, conv_path = _get_conversion(0.01, 'F/ft', 'C/m')
    assert _apply_conversion(0.01, conv_path) == conv

    conv, conv_path = _get_conversion(1, 'meter', 'inch')
    assert _apply_conversion(1, conv_path) == conv

    conv, conv_path = _converter(0.433, 'psi/ft', 'bar/m')
    assert round(_apply_conversion(0.433, conv_path), 6) == round(conv, 6)


def test__clean_print_conversion_path():
    """Validate normalization of the print-path flag to boolean values."""
    assert _clean_print_conversion_path() in (True, False)
    assert _clean_print_conversion_path(True) is True
    assert _clean_print_conversion_path(False) is False
    assert _clean_print_conversion_path(1) is True
    assert _clean_print_conversion_path(0) is False


def test_convert():
    """Validate public convert behavior for unitless and tabulated conversions."""
    assert convert(1, 'unitless', np.nan) == 1
    assert convert(1, 'unitless', None) == 1
    assert convert(1, None, np.nan) == 1
    assert convert(1, np.nan, np.nan) == 1
    assert convert(1, np.nan, 'unitless') == 1

    data = read_excel('./tests/conversions_check.xlsx')
    data = data.loc[data.skip != 'skip']  # only test rows not marked to skip
    error = 1E-4
    for i in data.index:
        if not isnan(data.loc[i, 'out']):
            print(data.loc[i, 'id'], ': converting', data.loc[i, 'source'], 'into', data.loc[i, 'target'])
            result = convert(data.loc[i, 'in'], data.loc[i, 'source'], data.loc[i, 'target'], False)
            print(result, data.loc[i, 'out'])
            assert abs(1 - result / data.loc[i, 'out']) < error


def test_convert_for_SimPandas():
    """Validate vectorized conversion helper compatibility with ndarray inputs."""
    array = np.random.rand(10)
    assert (convert_for_SimPandas(array, 'meter', 'litre') == array).all()
    assert (convert_for_SimPandas(array, 'm', 'yd') == convert(array, 'm', 'yd')).all()


def test_convert_numeric_range_boundaries():
    """Validate conversion behavior on extreme finite values and infinities."""
    assert convert(1e300, 'm', 'cm') == pytest.approx(1e302)
    assert convert(1e-300, 'm', 'cm') == pytest.approx(1e-298)
    assert np.isposinf(convert(np.inf, 'm', 'cm'))
    assert np.isneginf(convert(-np.inf, 'm', 'cm'))


def test_convert_for_simpandas_handles_nan_and_inf_arrays():
    """Vectorized conversion should preserve NaN/Inf semantics."""
    arr = np.array([0.0, np.nan, np.inf, -np.inf])
    result = convert_for_SimPandas(arr, 'm', 'cm')
    assert result[0] == pytest.approx(0.0)
    assert np.isnan(result[1])
    assert np.isposinf(result[2])
    assert np.isneginf(result[3])


def test_convert_complex_value_end_to_end():
    """Complex values should preserve complex arithmetic through conversion."""
    v = 1 + 2j
    out = convert(v, 'm', 'cm')
    assert out == pytest.approx((1 + 2j) * 100)


def test_convert_complex_array_end_to_end():
    """Complex ndarray conversion should scale each element correctly."""
    arr = np.array([1 + 1j, -2 + 0.5j], dtype=complex)
    result = convert_for_SimPandas(arr, 'm', 'cm')
    expected = arr * 100
    assert np.allclose(result, expected)


def test_case_insensitive_convert():
    # both low and mixed/upper case should work
    assert convert(1, 'METER', 'INCH') == pytest.approx(convert(1, 'meter', 'inch'))
    assert convert(1, 'rm3', 'SM3') == pytest.approx(convert(1, 'rm3', 'sm3'))
    assert convert(1, 'RB', 'STB') == pytest.approx(convert(1, 'rb', 'stb'))


def test_custom_units_snoot_regression():
    """Custom units should convert after registration, even if a prior lookup failed and was cached."""
    import unyts

    prev_raise_error = unyts.unyts_parameters_.raise_error_
    try:
        # Force a failed lookup first so older behavior would cache a None path.
        unyts.unyts_parameters_.raise_error_ = False
        assert convert(10, 'snoot', 'm') is None

        # Register custom unit and conversion pair.
        set_unit('snoot')
        set_conversion('snoot', 'm', lambda x: x * 1.7018)
        set_conversion('m', 'snoot', lambda x: x / 1.7018)

        # Conversion must work now (regression guard for stale cache entries).
        unyts.unyts_parameters_.raise_error_ = True
        assert convert(10, 'snoot', 'm') == pytest.approx(17.018)
    finally:
        unyts.unyts_parameters_.raise_error_ = prev_raise_error


def test_convertible_stb_day_sm3_day_warmup_regression():
    """Regression test for false-negative convertible on repeated calls after convert."""
    import unyts

    unyts.clean_memory()

    # initial convertible may be True/False depending on network warm-up, but convert must always succeed
    assert unyts.convertible('stb/day', 'sm3/day') is True
    assert unyts.convert(1, 'stb/day', 'sm3/day') == pytest.approx(0.1589872132943836)

    # after convert, convertible must remain True (no stale previous-state false negative)
    assert unyts.convertible('stb/day', 'sm3/day') is True


def test_convertible_with_previous_state_sentinel():
    """Emulate startup containing stale previous search state and still get true."""
    import unyts
    from unyts.database import units_network

    unyts.clean_memory()
    units_network.previous.append(('stb/day', 'sm3/day'))

    assert unyts.convertible('stb/day', 'sm3/day') is True
    assert unyts.convert(1, 'stb/day', 'sm3/day') == pytest.approx(0.1589872132943836)
    assert unyts.convertible('stb/day', 'sm3/day') is True
